<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RestorePackagesPath>$(MSBuildThisFileDirectory)obj/packages</RestorePackagesPath>
    <PackageVersion Condition="'$(PackageVersion)' == ''">999.0.0</PackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EverythingNetCore" Version="[$(PackageVersion)]" />
  </ItemGroup>
</Project>
